################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[tr]
languageName = "Türkçe"
languageCode = "tr"
contentDir = "content/turkish"
weight = 2
