############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Us"
url = "/#about"
weight = 2

[[main]]
name = "Projects"
url = "/#projects"
weight = 3

[[main]]
name = "Gallery"
url = "/gallery"
weight = 4

[[main]]
name = "Join Us"
url = "/#join"
weight = 5

[[main]]
name = "Events"
url = "https://www.instagram.com/weareoneintyouth" # TODO: change to events page
weight = 6

[[main]]
name = "Contact Us"
url = "/#contact"
weight = 7

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
