############# Turkish navigation ##############

# main menu
[[main]]
name = "Anasayfa"
url = "/"
weight = 1

[[main]]
name = "Hakkımızda"
url = "/#about"
weight = 2

[[main]]
name = "Projeler"
url = "/#projects"
weight = 3

[[main]]
name = "Bize katılın"
url = "/#join"
weight = 4

[[main]]
name = "Faaliyetler"
url = "https://www.instagram.com/weareoneintyouth" # TODO: change to events page
weight = 5

[[main]]
name = "Bize Ulaşın"
url = "/#contact"
weight = 6

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
